-- Create table for tracking daily user activity
CREATE TABLE IF NOT EXISTS user_activity_days (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  date DATE NOT NULL,
  test_count INTEGER DEFAULT 0,
  valid BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, date)
);

-- Add index for performance
CREATE INDEX IF NOT EXISTS idx_user_activity_days_user_date ON user_activity_days(user_id, date);

-- Enable RLS
ALTER TABLE user_activity_days ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view own activity" ON user_activity_days FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own activity" ON user_activity_days FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own activity" ON user_activity_days FOR UPDATE USING (auth.uid() = user_id);
